# Generated by Django 6.0.5 on 2026-05-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_number', models.CharField(max_length=64, unique=True)),
                ('surname', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField()),
                ('citizenship', models.CharField(max_length=128)),
                ('passport_number', models.CharField(max_length=64)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('visa_status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Invalid', max_length=16)),
                ('visa_validity', models.CharField(blank=True, max_length=64)),
                ('visa_type', models.CharField(max_length=64)),
                ('visit_purpose', models.CharField(max_length=128)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('duration_of_stay', models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True)),
                ('number_of_entries', models.PositiveIntegerField(default=1)),
                ('reference_number', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visa_photos/')),
            ],
            options={
                'verbose_name': 'Visa Record',
                'verbose_name_plural': 'Visa Records',
                'ordering': ['visa_number'],
            },
        ),
    ]
